'use strict';
const $=selector=>document.querySelector(selector);
const state={notes:[],byId:new Map(),categories:[],cards:[],cardBySource:new Map(),category:'',company:'',year:'',search:'',sort:'sources',view:'questions',selectedCard:null,answerOpen:false,listPage:1,selected:null,page:0};
const PAGE_SIZE=30;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const categoryLabel=card=>esc(card.category)+(card.topic&&card.topic!==card.category?' · '+esc(card.topic):'');
const selectedNote=()=>state.byId.get(state.selected);
const safeURL=value=>{try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='www.xiaohongshu.com'?u.href:'#';}catch{return '#';}};
const referenceURL=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:'#';}catch{return '#';}};
function highlight(value){const text=String(value??''),query=state.search.trim();if(!query)return esc(text);const at=text.toLocaleLowerCase().indexOf(query.toLocaleLowerCase());return at<0?esc(text):esc(text.slice(0,at))+'<mark>'+esc(text.slice(at,at+query.length))+'</mark>'+esc(text.slice(at+query.length));}
function filteredNotes(){return state.notes.filter(n=>(!state.category||n.categories.includes(state.category))&&(!state.company||n.companies.includes(state.company))&&(!state.year||n.date.startsWith(state.year))&&(!state.search.trim()||n.searchText.includes(state.search.trim().toLocaleLowerCase()))).sort((a,b)=>state.sort==='oldest'?a.date.localeCompare(b.date):b.date.localeCompare(a.date));}
const practiceRows=()=>filterPractice(state.cards,state.byId,state);
const resetScroll=()=>{const list=$('.question-sidebar'),reader=$('#answer-reader');if(list)list.scrollTop=0;if(reader)reader.scrollTop=0;};
function renderFilters(){const categories=['',...state.categories];$('#categories').innerHTML=categories.map(c=>`<button class="category ${c===state.category?'active':''}" data-category="${esc(c)}" aria-pressed="${c===state.category}">${c||'全部'}</button>`).join('');$('#reset').hidden=!(state.category||state.company||state.year||state.search);document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===state.view);b.setAttribute('aria-pressed',String(b.dataset.view===state.view));});$('#practice').hidden=state.view!=='questions';$('#note-list').hidden=state.view!=='notes';}
function render(){renderFilters();if(state.view==='notes'){renderNotes();return;}const rows=practiceRows();$('#result-count').innerHTML=`<strong>${rows.length}</strong> 道练习题 <span class="count-detail">相近问法已归并 · AI 参考答案</span>`;if(!rows.some(r=>r.card.id===state.selectedCard)){state.selectedCard=rows[0]?.card.id??null;state.answerOpen=false;}const pageCount=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));state.listPage=Math.min(state.listPage,pageCount);const page=rows.slice((state.listPage-1)*PAGE_SIZE,state.listPage*PAGE_SIZE);$('#question-list').innerHTML=page.length?page.map(({card,sources},i)=>{const companies=[...new Set(sources.flatMap(s=>state.byId.get(s.note_id).companies))];return `<button class="question-row ${card.id===state.selectedCard?'selected':''}" data-question="${esc(card.id)}" aria-current="${card.id===state.selectedCard}"><span class="question-row-top"><span class="category-label">${categoryLabel(card)}</span><span>${sources.length} 篇面经</span></span><h2>${highlight(card.question)}</h2><span class="question-companies">${esc(companies.slice(0,4).join(' · '))}${companies.length>4?' 等':''}</span></button>`;}).join(''):'<div class="empty"><h1>没有匹配的题目</h1><p>换一个筛选条件试试。</p><button data-reset>清除筛选</button></div>';$('#pagination').innerHTML=rows.length?`<button data-list-page="prev" ${state.listPage<=1?'disabled':''}>上一页</button><span>${state.listPage} / ${pageCount}</span><button data-list-page="next" ${state.listPage>=pageCount?'disabled':''}>下一页</button>`:'';renderAnswer(rows);}
function renderAnswer(rows=practiceRows()){const row=rows.find(r=>r.card.id===state.selectedCard);if(!row){document.body.classList.remove('question-reading');$('#answer-reader').innerHTML='<div class="empty"><h1>选择一道题开始练习</h1><p>每道题都保留原帖来源。</p></div>';return;}const {card,sources}=row;const date=sources.map(s=>state.byId.get(s.note_id).date).sort().at(-1);$('#answer-reader').innerHTML=`<article class="practice-article"><button class="question-mobile-back" id="question-back">← 返回题目列表</button><div class="answer-meta"><span class="category-label">${categoryLabel(card)}</span><span>来自 ${sources.length} 篇面经</span><span>最近原帖 ${date}</span></div><h1>${highlight(card.question)}</h1><div class="answer-actions"><button class="primary-button" id="toggle-answer" aria-expanded="${state.answerOpen}">${state.answerOpen?'收起参考回答':'查看参考回答'} <span>${state.answerOpen?'−':'+'}</span></button><button class="secondary-button" data-note="${sources[0].note_id}">查看原图与原帖 ↗</button></div>${state.answerOpen?`<section class="reference-answer"><div class="reference-heading"><h2>参考回答</h2><span>AI 整理</span></div><p class="short-answer">${highlight(card.answer)}</p><h3>回答思路</h3><ol class="answer-steps">${card.steps.map(s=>`<li>${highlight(s)}</li>`).join('')}</ol>${card.code?`<div class="code-caption">示例代码 · 以题干中的条件为准</div><pre class="answer-code"><code>${esc(card.code)}</code></pre>`:''}${card.pitfall?`<div class="pitfall"><span>注意</span><p>${esc(card.pitfall)}</p></div>`:''}${card.references?.length?`<details class="reference-links"><summary>延伸资料 · ${card.references.length}</summary>${card.references.map(r=>`<a href="${esc(referenceURL(r.url))}" target="_blank" rel="noopener noreferrer">${esc(r.title)} ↗</a>`).join('')}</details>`:''}<p class="answer-disclaimer">这是根据题干整理的答题参考，不是原帖作者或公司的标准答案。</p></section>`:`<div class="answer-collapsed"><span class="practice-symbol">?</span><div><strong>先想一想，你会怎么答？</strong><p>展开后查看简短回答、答题要点和常见误区。</p></div></div>`}<section class="question-sources"><h2>题目来源 <span>${sources.length}</span></h2><div class="source-list">${sources.slice(0,4).map(sourceRow).join('')}</div>${sources.length>4?`<details class="more-sources"><summary>展开其余 ${sources.length-4} 篇来源</summary>${sources.slice(4).map(sourceRow).join('')}</details>`:''}</section></article>`;}
function sourceRow(source){const n=state.byId.get(source.note_id);return `<div class="source-row"><div><span class="source-date">${esc(n.companies.join(' / '))} · ${n.date}</span><button class="source-title" data-note="${n.id}">${esc(n.title)}</button><details class="original-question"><summary>原帖中的问法</summary>${source.questions.map(q=>`<p>${esc(q)}</p>`).join('')}</details></div><a href="${esc(safeURL(n.url))}" target="_blank" rel="noopener noreferrer" aria-label="打开小红书原帖：${esc(n.title)}">原帖 ↗</a></div>`;}
function renderNotes(){const list=filteredNotes();$('#result-count').innerHTML=`<strong>${list.length}</strong> 篇面经 <span class="count-detail">原图与正文 · 2025 年起</span>`;$('#note-list').innerHTML=list.length?list.map(n=>`<button class="note-card" data-note="${n.id}" aria-label="打开面经：${esc(n.title)}"><div class="card-cover">${n.images[0]?`<img src="${n.images[0].src}" alt="${esc(n.title)}封面" loading="lazy">`:`<div class="text-cover">${esc(n.title)}</div>`}${n.images.length>1?`<span class="card-pages">${n.images.length} 张</span>`:''}</div><div class="card-content"><h2 class="card-title">${highlight(n.title)}</h2><div class="card-meta"><span>${esc(n.companies.join(' / '))}</span><time>${n.date}</time></div></div></button>`).join(''):'<div class="empty"><h1>没有匹配的面经</h1><button data-reset>清除筛选</button></div>';}
function reset(){Object.assign(state,{category:'',company:'',year:'',search:'',listPage:1,selectedCard:null});for(const field of ['search','company','year'])$('#'+field).value='';render();resetScroll();}
$('#categories').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b){state.category=b.dataset.category;state.listPage=1;state.selectedCard=null;render();resetScroll();}});
for(const field of ['company','year','sort'])$('#'+field).addEventListener('change',e=>{state[field]=e.target.value;state.listPage=1;state.selectedCard=null;render();resetScroll();});
let searchTimer;$('#search').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.search=e.target.value;state.listPage=1;state.selectedCard=null;render();resetScroll();},150);});$('#reset').onclick=reset;
document.querySelector('.view-switch').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b){state.view=b.dataset.view;document.body.classList.remove('question-reading');render();}});
$('#question-list').addEventListener('click',e=>{const b=e.target.closest('[data-question]');if(b){state.selectedCard=b.dataset.question;state.answerOpen=false;render();$('#answer-reader').scrollTop=0;document.body.classList.add('question-reading');history.replaceState(null,'','#question/'+state.selectedCard);}if(e.target.closest('[data-reset]'))reset();});
$('#pagination').addEventListener('click',e=>{const b=e.target.closest('[data-list-page]');if(b){state.listPage+=b.dataset.listPage==='next'?1:-1;state.selectedCard=practiceRows()[(state.listPage-1)*PAGE_SIZE]?.card.id??null;state.answerOpen=false;render();$('.question-sidebar').scrollTop=0;}});
$('#answer-reader').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='toggle-answer'){state.answerOpen=!state.answerOpen;renderAnswer();}else if(b.id==='question-back'){document.body.classList.remove('question-reading');}else if(b.dataset.note){openNote(b.dataset.note);}});
$('#note-list').addEventListener('click',e=>{const b=e.target.closest('[data-note]');if(b)openNote(b.dataset.note);if(e.target.closest('[data-reset]'))reset();});
function questionIndex(n){const qs=n.questions.filter(q=>!state.category||q.category===state.category);return `<details class="question-index"><summary>本篇题目 · ${qs.length} 条</summary><div class="question-items">${qs.map(q=>{const origin=q.origins.find(o=>/^图片\d+$/.test(o)),cardIds=state.cardBySource.get(n.id+'\0'+q.text)||[];return `<div class="question-item"><span class="tag">${q.category}</span>${highlight(q.text)}<div class="question-inline-actions">${cardIds.map((id,i)=>`<button data-answer="${esc(id)}">查看参考${cardIds.length>1?' '+(i+1):'回答'} →</button>`).join('')}${origin?`<button data-origin="${Number(origin.slice(2))-1}">看${origin}</button>`:''}</div></div>`;}).join('')}</div></details>`;}
function goAnswer(id){const card=state.cards.find(c=>c.id===id);if(!card)return;Object.assign(state,{view:'questions',selectedCard:id,answerOpen:true,category:card.category,search:''});$('#search').value='';let rows=practiceRows();if(!rows.some(r=>r.card.id===id)){state.company='';state.year='';$('#company').value='';$('#year').value='';rows=practiceRows();}state.listPage=Math.floor(rows.findIndex(r=>r.card.id===id)/PAGE_SIZE)+1;$('#detail').close();render();$('#answer-reader').scrollTop=0;document.body.classList.add('question-reading');history.replaceState(null,'','#question/'+id);}
function renderContent(){const n=selectedNote(),list=filteredNotes(),index=list.findIndex(i=>i.id===n.id);$('#content-panel').innerHTML=`<div class="author-row"><span class="author-avatar" aria-hidden="true">${esc((n.author||n.companies[0]).slice(0,1))}</span><span class="author-name">${esc(n.author||n.companies.join(' / '))}</span><a class="source-link" href="${esc(safeURL(n.url))}" target="_blank" rel="noopener noreferrer">查看原帖</a></div><div class="post-scroll"><h1 class="post-title">${highlight(n.title)}</h1><p class="post-body">${highlight(n.body||'这篇面经的内容在图片里，点击图片可放大查看。')}</p><div class="post-tags">${n.categories.map(c=>`<span>#${c}</span>`).join('')}</div><div class="post-date"><time datetime="${n.date}">${n.date.replaceAll('-','-')}</time> · ${esc(n.companies.join(' / '))}</div>${questionIndex(n)}</div><footer class="post-footer"><button class="text-button" id="copy-body" ${n.body?'':'disabled'}>复制正文</button><div class="note-navigation"><button id="prev-note" ${index<=0?'disabled':''}>上一篇</button><span>${index<0?'—':index+1} / ${list.length}</span><button id="next-note" ${index<0||index===list.length-1?'disabled':''}>下一篇</button></div></footer>`;}
function renderImage(){const n=selectedNote(),img=n.images[state.page];if(!img){$('#visual-panel').innerHTML='<div class="no-image">这篇面经以文字分享</div>';return;}$('#visual-panel').innerHTML=`<button class="image-button" id="open-zoom" aria-label="放大第 ${state.page+1} 张原图"><img class="original-image" src="${img.src}" alt="${esc(n.title)}，第 ${state.page+1} 张原图"></button><span class="image-counter">${state.page+1} / ${n.images.length}</span>${n.images.length>1?`<button class="image-arrow image-prev" data-page="prev" aria-label="上一张图片" ${state.page===0?'disabled':''}>‹</button><button class="image-arrow image-next" data-page="next" aria-label="下一张图片" ${state.page===n.images.length-1?'disabled':''}>›</button><div class="image-dots" aria-label="选择图片">${n.images.map((im,i)=>`<button class="image-dot ${i===state.page?'active':''}" data-image="${i}" aria-label="查看第 ${i+1} 张图片" aria-pressed="${i===state.page}"></button>`).join('')}</div>`:''}`;const displayed=$('.original-image');displayed.addEventListener('load',fitDetail,{once:true});if(displayed.complete)fitDetail();}
function fitDetail(){const dialog=$('#detail'),img=$('.original-image');if(document.documentElement.clientWidth<=700){dialog.style.height='';return;}if(!dialog.open||!img?.naturalWidth)return;const width=$('#visual-panel').clientWidth;dialog.style.height=Math.min(document.documentElement.clientHeight-64,Math.max(520,width*img.naturalHeight/img.naturalWidth))+'px';}
window.addEventListener('resize',fitDetail);
function openNote(id){if(!state.notes.some(n=>n.id===id))return;state.selected=id;state.page=0;renderContent();renderImage();if(!$('#detail').open)$('#detail').showModal();fitDetail();$('#detail').scrollTop=0;history.replaceState(null,'','#note/'+id);}
function changeImage(index){const n=selectedNote();if(!n?.images.length)return;state.page=Math.max(0,Math.min(index,n.images.length-1));renderImage();if($('#zoom').open)renderZoom();}
function renderZoom(){const n=selectedNote();$('#zoom-image').src=n.images[state.page].src;$('#zoom-image').alt=`${n.title}，第 ${state.page+1} 张原图`;$('#zoom-caption').textContent=`${state.page+1} / ${n.images.length}`;$('#zoom-prev').disabled=state.page===0;$('#zoom-next').disabled=state.page===n.images.length-1;$('.zoom-scroll').scrollTop=0;}

$('#detail').addEventListener('click',async e=>{if(e.target===$('#detail')){$('#detail').close();return;}const b=e.target.closest('button');if(!b)return;if(b.id==='close-detail'){$('#detail').close();return;}if(b.dataset.answer){goAnswer(b.dataset.answer);return;}if(b.id==='open-zoom'){renderZoom();$('#zoom').showModal();return;}if(b.dataset.page){changeImage(state.page+(b.dataset.page==='next'?1:-1));return;}if(b.dataset.image!==undefined){changeImage(Number(b.dataset.image));return;}if(b.dataset.origin!==undefined){const i=selectedNote().images.findIndex(img=>img.index===Number(b.dataset.origin));if(i>=0){changeImage(i);$('#visual-panel').scrollIntoView({block:'start',behavior:'smooth'});}return;}if(b.id==='prev-note'||b.id==='next-note'){const list=filteredNotes(),index=list.findIndex(n=>n.id===state.selected),target=list[index+(b.id==='next-note'?1:-1)];if(target)openNote(target.id);return;}if(b.id==='copy-body'){try{await navigator.clipboard.writeText(selectedNote().body);b.textContent='已复制';b.classList.add('toast');setTimeout(()=>{b.textContent='复制正文';b.classList.remove('toast');},1600);}catch{b.textContent='请选中文字复制';}}});
$('#detail').addEventListener('close',()=>history.replaceState(null,'',location.pathname+location.search+(state.selectedCard?'#question/'+state.selectedCard:'')));
$('#zoom-close').onclick=()=>$('#zoom').close();$('#zoom-prev').onclick=()=>changeImage(state.page-1);$('#zoom-next').onclick=()=>changeImage(state.page+1);$('#zoom').addEventListener('click',e=>{if(e.target===$('#zoom'))$('#zoom').close();});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if($('#detail').open||$('#zoom').open){if(e.key==='ArrowLeft'){e.preventDefault();changeImage(state.page-1);}if(e.key==='ArrowRight'){e.preventDefault();changeImage(state.page+1);}}else if(e.key==='/'){e.preventDefault();$('#search').focus();}});
let touchStart=null;$('#visual-panel').addEventListener('touchstart',e=>{touchStart={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY};},{passive:true});$('#visual-panel').addEventListener('touchend',e=>{if(!touchStart)return;const dx=e.changedTouches[0].clientX-touchStart.x,dy=e.changedTouches[0].clientY-touchStart.y;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.4)changeImage(state.page+(dx<0?1:-1));touchStart=null;},{passive:true});
async function init(){try{const responses=await Promise.all([fetch('notes.json'),fetch('practice.json')]);if(responses.some(r=>!r.ok))throw Error('load failed');const [notes,practice]=await Promise.all(responses.map(r=>r.json()));state.notes=notes.notes;state.byId=new Map(state.notes.map(n=>[n.id,n]));state.categories=notes.categories;state.cards=practice.cards;for(const c of state.cards)for(const source of c.sources)for(const question of source.questions)state.cardBySource.set(source.note_id+'\0'+question,[...(state.cardBySource.get(source.note_id+'\0'+question)||[]),c.id]);for(const n of state.notes)n.searchText=[n.title,n.body,...n.companies,...n.questions.map(q=>q.text)].join('\n').toLocaleLowerCase();const companies=[...new Set(state.notes.flatMap(n=>n.companies))].sort((a,b)=>state.notes.filter(n=>n.companies.includes(b)).length-state.notes.filter(n=>n.companies.includes(a)).length);$('#company').innerHTML='<option value="">全部公司</option>'+companies.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');const hash=location.hash.slice(1),qid=hash.startsWith('question/')?hash.slice(9):null;if(qid&&state.cards.some(c=>c.id===qid)){state.selectedCard=qid;state.listPage=Math.floor(practiceRows().findIndex(r=>r.card.id===qid)/PAGE_SIZE)+1;}render();if(qid)document.body.classList.add('question-reading');if(hash.startsWith('note/'))openNote(hash.slice(5));}catch{$('#result-count').textContent='加载未完成';$('#question-list').innerHTML=$('#answer-reader').innerHTML='<div class="empty"><h1>题目暂时没有加载成功</h1><p>请刷新页面重试。</p><button onclick="location.reload()">重新加载</button></div>';}}
init();
